import java.awt.*;
import java.awt.event.*;
import java.util.TimerTask;
import java.util.Timer;


public class TabelloneFinestra extends javax.swing.JFrame {

    /**
     * Creates new form TabelloneFinestra
     * @param partita
     */
    Partita partita;
    java.util.Timer timer=new java.util.Timer();
    TimerTask task=new TimerTask() {
        @Override
        public void run() {
            if (Inserimento.secondi>=0) {
                punteggioRandom(partita);
                String time = String.format("%02d:%02d", Inserimento.secondi / 60, Inserimento.secondi-- % 60);
                tempo.setText(time);
                gestionePunteggio(partita);
            }
            else {
                finePartita();
            }
        }        
    };
        
    public TabelloneFinestra(Partita partita,int secondi) {
        initComponents();
        this.partita=partita;
        nomeCasaTab.setText(partita.getSquadraLocale().getNomeSquadra());
        allenatoreCasaTab.setText(partita.getSquadraLocale().getNomeAllenatore());
        dirigenteCasaTab.setText(partita.getSquadraLocale().getNomeDirigente());
        
        nomeOspiteTab.setText(partita.getSquadraOspite().getNomeSquadra());
        allenatoreOspiteTab.setText(partita.getSquadraOspite().getNomeAllenatore());
        dirigenteOspiteTab.setText(partita.getSquadraOspite().getNomeDirigente());
        
        puntiCasa.setText(Integer.toString(0));
        puntiOspite.setText(Integer.toString(0));
        
        
        azzeraPunteggio.setEnabled(false);
        finePartita.setEnabled(true);
        
        esito.setVisible(false);
        
        timer.scheduleAtFixedRate(task, 0, 1000);
        
    }
    int puntiSquadraCasa,puntiSquadraOspite;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton12 = new javax.swing.JButton();
        nomeCasaTab = new javax.swing.JLabel();
        nomeOspiteTab = new javax.swing.JLabel();
        allenatoreCasaTab = new javax.swing.JLabel();
        dirigenteOspiteTab = new javax.swing.JLabel();
        allenatoreOspiteTab = new javax.swing.JLabel();
        dirigenteCasaTab = new javax.swing.JLabel();
        puntiCasa = new javax.swing.JLabel();
        puntiOspite = new javax.swing.JLabel();
        esito = new javax.swing.JLabel();
        finePartita = new javax.swing.JButton();
        azzeraPunteggio = new javax.swing.JButton();
        tempo = new javax.swing.JLabel();

        jButton12.setText("jButton12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabellone");
        setLocation(new java.awt.Point(330, 100));
        setSize(new java.awt.Dimension(648, 441));

        nomeCasaTab.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nomeCasaTab.setText("Nome");

        nomeOspiteTab.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nomeOspiteTab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nomeOspiteTab.setText("Nome");

        allenatoreCasaTab.setText("Allenatore");

        dirigenteOspiteTab.setText("Dirigente");

        allenatoreOspiteTab.setText("Allenatore");

        dirigenteCasaTab.setText("Dirigente");

        puntiCasa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        puntiCasa.setText("Punti");

        puntiOspite.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        puntiOspite.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        puntiOspite.setText("Punti");

        esito.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        esito.setForeground(new java.awt.Color(255, 51, 51));
        esito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        esito.setText("Esito");
        esito.setToolTipText("");
        esito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        finePartita.setText("Fine Partita");
        finePartita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finePartitaActionPerformed(evt);
            }
        });

        azzeraPunteggio.setText("Azzera Punteggio");
        azzeraPunteggio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azzeraPunteggioActionPerformed(evt);
            }
        });

        tempo.setText("Tempo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeCasaTab, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nomeOspiteTab, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(puntiCasa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntiOspite))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dirigenteCasaTab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dirigenteOspiteTab))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(allenatoreCasaTab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(allenatoreOspiteTab)))
                .addGap(35, 35, 35))
            .addComponent(esito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(finePartita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(azzeraPunteggio, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addGap(252, 252, 252))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tempo)
                        .addGap(303, 303, 303))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tempo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeOspiteTab, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(nomeCasaTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allenatoreCasaTab, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allenatoreOspiteTab))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirigenteCasaTab)
                    .addComponent(dirigenteOspiteTab))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puntiCasa)
                    .addComponent(puntiOspite))
                .addGap(10, 10, 10)
                .addComponent(azzeraPunteggio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finePartita, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(esito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finePartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finePartitaActionPerformed
        finePartita();
        timer.cancel();
    }//GEN-LAST:event_finePartitaActionPerformed

    private void azzeraPunteggioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azzeraPunteggioActionPerformed
        finePartita.setBackground(null);
        partita.azzeraPunteggio();
        finePartita.setEnabled(true);
        
        puntiCasa.setText(Integer.toString(0));
        puntiOspite.setText(Integer.toString(0));
        gestionePunteggio(partita);
        esito.setVisible(false);
        
    }//GEN-LAST:event_azzeraPunteggioActionPerformed
    
    public void gestionePunteggio(Partita partita) {
        if (partita.getPuntiSquadraLocale()==0 && partita.getPuntiSquadraOspite()==0) azzeraPunteggio.setEnabled(false);
        else azzeraPunteggio.setEnabled(true);
        
    }
    
    javax.swing.Timer lampeggio = new javax.swing.Timer(500, new ActionListener() {
            boolean visibile = true;

            @Override
            public void actionPerformed(ActionEvent e) {
                visibile = !visibile;
                esito.setVisible(visibile ? true : false);
            }
        });
    
    public void punteggioRandom(Partita partita) {
        int random=(int) (Math.random()*3);
        switch (random) {
            case 0:
                break;
            case 1:
                partita.aggiungiPuntiLocaliRandom();
                puntiCasa.setText(Integer.toString(partita.getPuntiSquadraLocale()));
                break;
            case 2:
                partita.aggiungiPuntiOspitiRandom();
                puntiOspite.setText(Integer.toString(partita.getPuntiSquadraOspite()));
                break;
        }
    }
    
    public void finePartita() {
        finePartita.setBackground(Color.red);
        finePartita.setEnabled(false);
        azzeraPunteggio.setEnabled(true);
        
        esito.setVisible(true);
        if (partita.vincitore()==null) esito.setText("Pareggio");
        else esito.setText("Vincitore: "+partita.vincitore());
        
        lampeggio.start();
        azzeraPunteggio.setEnabled(false);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allenatoreCasaTab;
    private javax.swing.JLabel allenatoreOspiteTab;
    private javax.swing.JButton azzeraPunteggio;
    private javax.swing.JLabel dirigenteCasaTab;
    private javax.swing.JLabel dirigenteOspiteTab;
    private javax.swing.JLabel esito;
    private javax.swing.JButton finePartita;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel nomeCasaTab;
    private javax.swing.JLabel nomeOspiteTab;
    private javax.swing.JLabel puntiCasa;
    private javax.swing.JLabel puntiOspite;
    private javax.swing.JLabel tempo;
    // End of variables declaration//GEN-END:variables
}
